### ISSUE TITLE
table name quoted wrong

### ISSUE THREAD

**Issue by kevenli** [gijzelaerr/sqlalchemy-monetdb#11] opened 2016-12-20 06:17 UTC
Hi, i'm using sqlalchemy-monetdb against monetdb.
and I met a problem when running a select statement, the error is : 

OperationalError: (pymonetdb.exceptions.OperationalError) SELECT: no such table 'abc_ds2_EJB09S'
 [SQL: u'SELECT "ID" \nFROM "abc_ds2_EJB09S"\nLIMIT 10 OFFSET 0']

it seems the table name is quoted with double-quote, but i think it is incorrect. the table does exist and my  traditional way(combine sql manually) works.

**Comment by gijzelaerr** [comment] 2017-09-20 12:55
hi @kevenli sorry for the delay. Is this still an issue for you? If so can you state which pymonetdb and sqlalchemy-monetdb version you are using? and what is the python code you use?

**Comment by gijzelaerr** [comment] 2017-10-18 14:20
closing this issue since probably not a problem with this dialect. Please reopen if the problem is not solved.

**Closed by gijzelaerr** 2017-10-18 14:20 UTC
